spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/arin
  redis:
    host: redis
    port: 6379
    timeout: 2000

app:
  oauth2:
    redirect-uri: http://localhost/oauth/success-popup
    allowed-origins:
      - http://localhost
proxy:
  upstream: http://fastapi:9000
